### ISSUE TITLE
Offline sync condensing logic causes problems for foreign keys

### ISSUE THREAD

**Issue by seanfisher** [Azure/azure-mobile-apps-net-client#161] opened 2016-06-14 16:33 UTC
This is a continuation of Azure/azure-mobile-services#871. 

Basically,

```
insert in table A VALUES {id: a, value: a1, foreignkey: null}
insert in table B VALUES {id: b, value: b1}
update table A VALUES {id: a, value: a2, foreignkey: b}
```

...and syncing breaks. The whole point of a **queue** for operations is to let actions happen on the server in the _same order_ they happened on the client. This behavior of condensing changes on the client fundamentally breaks that paradigm and renders the operations queue useless for all but the most basic entities with no server-side relationships. This condensing behavior means that the library might as well forget about having a queue and start to parallelize all of the requests to the server in no particular order (or a naive order like inserts first, then updates) to speed things up, because the library can't be relied upon for order-related changes as it currently stands.

The most logical solution is to enable change tracking in Azure Mobile Apps client. I know there is some resistance to this but the library may just have to bite the bullet and do it, especially since related issues like #116 and others are cropping up that would be much easier to solve with change tracking. This change-tracking behavior could even be opt-in to make it a non-breaking change.

**Comment by lindydonna** [comment] 2016-06-14 23:34
This is definitely a big limitation of the SDK that needs to be fixed. The problem is that any fix is expensive and complex, and introduces its own issues, which is why the fix is taking so long.

The condensing logic has problems, but it simplify some things. The main reason it was introduced was to avoid the problem of conflicts when there are multiple edits to the same entity. If you have the following changes:
1.	A.a = "bar"
2.	Other changes
3.	A.b = "foo"

Then what happens if change #1 has a conflict with the server copy?  Then you have to resolve the conflict, and then figure how to merge in change #3. Even if there is no conflict, then A definitely has some changed fields--at least the Version field if not others. So, the SDK needs to then handle field level merges and allow developers to customize the behavior. Plus, the SDK needs to track individual field changes, and not just object changes.

In order to avoid all of this complexity, the condensing logic was introduced, but it has the drawbacks of not keeping things in order when other objects were changing, which is a big problem. 

There are other solutions beyond field-level change tracking, however. For instance, if the SDK let you customize the policy of how to do the condensing, that would be sufficient for this example. Right now, the original change is replaced, so in the example above, change #1 and #3 are merged and replace change #1. If it were possible to customize this so that change #3 was replaced, then the other operations would happen first and things would work out fine for this example.

The only case that wouldn’t work is if there were circular dependencies between two objects, which is generally uncommon.

**Comment by seanfisher** [comment] 2016-06-15 00:21
@lindydonna I agree that this looks like a complex change, but I also agree with you that there may be a middle ground that will solve the foreign key issue without tracking of every single field-level change. 

Here's a quick thought: what if updates are never condensed into inserts, but updates are allowed to be condensed into other updates? For example:

    1. insert in table A VALUES {id: a, value: a1, foreignkey: null}
    2. insert in table B VALUES {id: b, value: b1}
    3. update table A VALUES {id: a, value: a2, foreignkey: b}
    4. update table A VALUES {id: a, value: a3, foreignkey: b}

So what if 3 was never condensed into 1, but 4 was condensed into 3?

It would require adding a column to `__operations` (only used in insert statements) where a serialized version of the inserted entity is kept. This column represents the entity at the time it was inserted into the local sync table. Then, updates act as they do now and can update the sync tables, add update operations into `__operations`, and condense subsequent update operations into one update. In our example above, the end result of the local database before syncing would be:

Table A:

id | value | foreignKey
---- | ---- | ----
a | a3 | b

Table B:

id | value
---- | ----
b | b1

__operations:

...otherColumns | type | table | entityId | serializedEntity
---- | ---- | ---- | ---- | ----
... | insert | A | a | `{id: "a", value: "a1", foreignKey: null}`
... | insert | B | b | `{id: "b", value: "b1"}`
... | update | A | a | null

This appears to solve the foreign key problem while still allowing some condensing to avoid the problems you mentioned.

**Comment by lindydonna** [comment] 2016-06-15 01:26
That's an interesting idea, since it would at least solve the conflict problem. You'd still have to do merges though, because the insert would return a new record, with a new version field. I suppose you could use the previously serialized entity to see what fields changed, and merge into the update if only the version column changed. Any other merge would not be possible, since the update doesn't track the changed columns.

It seems like an option for customizing the condensing in terms of which order in the operation queue would be simpler though, and would avoid the changes to the operation queue design. Wouldn't that address your particular situation?

**Comment by seanfisher** [comment] 2016-06-17 16:17
Well, on initial glance that looks like it might solve the issue, but consider the following situation:

    insert in table A VALUES {id: a, value: a1}
    insert in table B VALUES {id: b, value: b1, foreign key: A}
    update table A VALUES {id: a, value: a2}

In this case if we condensed down instead of up it would end up looking like:

    insert in table B VALUES {id: b, value: b1, foreign key: A}
    insert into table A VALUES {id: a, value: a2}

Which also doesn't work.

**Comment by lindydonna** [comment] 2016-06-17 16:38
Right, in this example you would condense to update the existing record. The actual API would take your dependencies and figure out the right logic, so it would be unlikely that you would have to directly specificity the collapse order for each record type. 

The only case that wouldn't work is circular dependencies.

**Comment by shrishrirang** [comment] 2016-06-20 20:05
The proposal by @seanfisher is interesting! One issue I see with that is that if the insert (for table A) conflicts, the user would have to resolve the conflict looking at a record value from the past and this looks little unnatural to me. Imagine I having to resolve an old Todo note while pushing the Todo list on my phone to be able to push the latest Todo update.

@seanfisher: If the SDK lets you define foreign relationships (say A foreign references B, B references C and D) and performs push in the following order, will that address your issues:

1. Push inserts and updates to D, C, B and A in that order
2. Push deletes in A, B, C and D in that order

It is possible to come up with a linear order as long as there are no cyclic dependencies.

**Comment by shrishrirang** [comment] 2016-06-21 20:26
Also, what happens in the following scenario if updates are collapsed into earlier updates?

    1. insert in table A VALUES {id: a, value: a1, foreignkey: null}
    2. update table A VALUES {id: a, value: a2, foreignkey: null}
    2. insert in table B VALUES {id: b, value: b1}
    4. update table A VALUES {id: a, value: a3, foreignkey: b}

**Comment by adrianhall** [comment] 2017-04-17 01:15
Closing off a number of issues today.

We will NOT be supporting foreign keys in this library.

I'm happy to accept a PR that adjusts the sequencing for collapsing of the requests.  However, right now, we have no intention of supporting transactions, which is what is really required.

**Closed by adrianhall** 2017-04-17 01:15 UTC
