### ISSUE TITLE
MobileServiceInvalidOperationException.Value is sometimes null

### ISSUE THREAD

**Issue by migig** [Azure/azure-mobile-apps-net-client#179] opened 2016-07-10 06:52 UTC
I've implemented conflict resolution via `IMobileServiceSyncHandler.ExecuteTableOperationAsync()`.

I catch `MobileServiceConflictException` and `MobileServicePreconditionFailedException`. Then I inspect the server's value via `exception.Value`, and decide how to handle the conflict.

Problem is, I expect that value to be populated, but sometimes it's `null`. I can't pin down when that happens though. Sometimes it is and sometimes it isn't!

**Comment by migig** [comment] 2016-07-10 08:20
I just found something interesting - [in this example](http://github.com/Azure/mobile-services-samples/blob/master/TodoOffline/Xamarin.iOS/XamarinOffline.iOS/SyncHandler.cs#L56), it says that this can happen for HTTP status code 409 ("Precondition Failed").

But, is this a bug or by design??

**Comment by fabiocav** [comment] 2016-07-11 17:32
@migig, there have been discussions on changing this behavior, but with the current implementation, this is by design. The sample you have linked to shows how to handle those conflicts, so I'll be closing this issue, but feel free to ask any questions if you need more information.

**Closed by fabiocav** 2016-07-11 17:32 UTC

**Comment by migig** [comment] 2016-07-12 05:09
@fabiocav Thanks for the confirmation.

I'm new to this SDK. That workaround seems a little "hackish" (no offense, I'm sure there's a good reason for it), so is it expected to work always? i.e. If I implement that workaround can I just forget about this problem?

**Comment by lindydonna** [comment] 2016-07-12 21:01
@migig It will definitely always work to do a server call to get the current value, though it's possible that the server SDK in the future would send back the conflicted value (but probably in a major revision). The reason for the behavior is that not all data providers automatically return the current value, so it can result in more database calls, which might be potentially unnecessary.

**Comment by migig** [comment] 2016-07-14 17:55
@lindydonna Thanks for explaining the by-design reasoning, it makes sense now.
