### ISSUE TITLE
SQLitePCLRaw Updated with Breaking Changes

### ISSUE THREAD

**Issue by tomeverin** [Azure/azure-mobile-apps-net-client#542] opened 2020-05-18 22:20 UTC
Azure.Mobile.Client.SQLiteStore needs to be updated for compatibility with SQLitePCLRaw.bundle_green > 2.0

https://github.com/ericsink/SQLitePCL.raw/blob/master/v2.md#source-level-breaking-changes

**Comment by MatkovIvan** [comment] 2020-05-19 06:51
Duplicate of #533

**Closed by MatkovIvan** 2020-05-19 06:51 UTC
