### ISSUE TITLE
Custom Auth without using App Service Authentication

### ISSUE THREAD

**Issue by FrancoisM** [Azure/azure-mobile-apps-net-client#78] opened 2016-02-19 15:24 UTC
Updating comment based on Adrian's explanation below:

Use LoginAsync() to perform custom authentication actions where the action is embedded in my code base rather than using the Authentication / Authorization service provided by Azure App Service.

**Comment by Reminouche** [comment] 2016-02-19 16:32
You can create a handler for add this header request.

```C#
public class ZumoAuthHeaderHandler : DelegatingHandler
{
		protected override Task<HttpResponseMessage> SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
		{
			if (string.IsNullOrWhiteSpace(AccountService.Instance.AuthenticationToken))
			{
				throw new InvalidOperationException("User is not currently logged in");
			}

			request.Headers.Add("X-ZUMO-AUTH", AccountService.Instance.AuthenticationToken);

			return base.SendAsync(request, cancellationToken);
		}
}
```

and use like this: 

```C#
using (var handler = new ZumoAuthHeaderHandler ()) 
{
				using (var client = MobileServiceClientFactory.CreateClient (handler)) 
				{
				}
}
```

I don't know if this is the best solution but it works

**Comment by FrancoisM** [comment] 2016-02-19 16:37
That's exactly what I'm in the middle of doing :-)
Tks for the code though I'll update it for ZUMU-API-VERSION.

However, my question remains, isn't  the ZUMO-API-VERSION key supposed to be in all Mobile App http request by default? What's the point of LoadAsync if it can't be used?

**Comment by FrancoisM** [comment] 2016-02-19 16:50
Meanwhile I tried that:

`public MobileServiceClient MobileService { get; } = new MobileServiceClient("https://myservice.azurewebsites.net", new ZumoAuthHeaderHandler());`
`public class ZumoAuthHeaderHandler : DelegatingHandler
    {
        protected override Task<HttpResponseMessage> SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
        {
            request.Headers.Add("ZUMO-API-VERSION", "2.0.0");
            return base.SendAsync(request, cancellationToken);
        }
    }`
`await MobileService.LoginAsync("CustomAuth", challenge);`

However, I still get the error 400. The overridden SendAsync is never hit.

**Comment by Reminouche** [comment] 2016-02-19 16:55
Have you activated authentification on your rest api ? with [Authorize] annotation on your method controller ?

If you don't have authentication, you don't need zumo auth handler.

**Comment by FrancoisM** [comment] 2016-02-19 16:55
I noticed that LoginAsync will at some points call:

`return client.HttpClient.RequestWithoutHandlersAsync(HttpMethod.Post, pathAndQuery, client.CurrentUser, token.ToString());`

From the name of the method I understand why my override is not hit.

**Comment by FrancoisM** [comment] 2016-02-19 16:58
@Reminouche : yes authentication is activated. I can log with Facebook. My custom login controller works as well (tested with Fiddler). I'm sure I could have it worked using InvokeApiAsync and passing ZUMO-API-VERSION as a query string but I feel I'm missing some logic with LoginAsync which should do what it says.

**Comment by Reminouche** [comment] 2016-02-19 17:32
Hum, strange it works fine with me. You need add ZUMO-API-VERSION and X-ZUMO-AUTH.

**Comment by FrancoisM** [comment] 2016-02-19 17:34
X-ZUMO-AUTH is required post authentication.
Anyway, for the time bieng I'll use the following based on this Library source code. It works.

`private const string LoginAsyncAuthenticationTokenKey = "authenticationToken";

        internal async Task MyLoginAsync(string ApiName, JObject token)
        {
            JToken authToken = await MobileService.InvokeApiAsync($"{MobileService.LoginUriPrefix}/{ApiName}", token, HttpMethod.Post, new Dictionary<string, string> { { "ZUMO-API-VERSION", "2.0.0" } });
            if (authToken != null)
            {
                // Get the Mobile Services auth token and user data
                MobileService.CurrentUser = new MobileServiceUser((string)authToken["user"]["userId"]);
                MobileService.CurrentUser.MobileServiceAuthenticationToken = (string)authToken[LoginAsyncAuthenticationTokenKey];
            }  
        }`

**Comment by Reminouche** [comment] 2016-02-19 17:38
Ho yeah, you are right (about X-ZUMO-AUTH). Hum... very strange, wich client plateform do you use ?

**Comment by FrancoisM** [comment] 2016-02-19 17:45
I'm testing on iOS right now.

I'm trying to use LoginAsync not to use a custom zumo Handler.
When I log with Facebook, I can access my [Authorize] controllers without having to do anything more in code than if the controller were not [Authorize].
However, with a custom login based on the code I just posted, I got error 401. I thought setting MobileService.CurrentUser.MobileServiceAuthenticationToken would make the trick but it doesn't.

**Comment by FrancoisM** [comment] 2016-02-19 17:48
What I'm trying to do is just follow that tip:
"Using the loginAsync() approach ensures that the authentication token is attached to every subsequent call to the service."
from
https://azure.microsoft.com/en-us/documentation/articles/app-service-mobile-dotnet-backend-how-to-use-server-sdk/#custom-auth

**Comment by FrancoisM** [comment] 2016-02-19 17:53
ps: now that think about it, the RequestWithoutHandlersAsync for LoginAsync is certainly due to the fact that other api calls use a default zumo handler which sends the token (well that's what I expect but don't observe) but for login that would be a bad idea a the token is not available yet.

**Comment by FrancoisM** [comment] 2016-02-19 18:08
Actually, once custom logged, request DO have zumo-api-version AND x-zumo-auth with the token. However I still get 401.

**Comment by FrancoisM** [comment] 2016-02-19 18:12
I had a typo on the issuer of my custom auth controller :-)
No 401 anymore.

So if I summarize that post the only question is why ins't there a zumo-api-version key in the header of the request made by calling

`
 Task<MobileServiceUser> LoginAsync(string provider, JObject token) `

**Comment by gb92** [comment] 2016-03-15 16:18
Sorry for the delayed response to this thread. Auth is handled by [App Service Authentication/Authorization](https://azure.microsoft.com/en-us/blog/announcing-app-service-authentication-authorization/) and will have separate versioning from Mobile Apps, so the decision was made to not send the ZUMO-API-VERSION header on Login requests.

**Comment by FrancoisM** [comment] 2016-03-15 16:38
I'm lost. Using App service authentication is the end goal. However, it can't work by calling loginasync as explained in tutorials re App service authentication.

**Comment by adrianhall** [comment] 2016-03-25 00:18
Hi Francois,

I believe the actual intent of this has been lost in translation.  My belief is:

* You have configured Azure App Service Authentication / Authorization with a Facebook login
* You are successfully logging in when you point your browser to /.auth/login/facebook
* You are not successfully logging in when you use .LoginAsync('facebook', token);

I don't believe the ZUMO-API-VERSION has anything to do with it.  Can you please confirm my understanding is correct?  Can you also, if correct, please post a link to your repository and highlight the code, or post new code snippets here showing the complete flow for your login.

Thanks,

**Comment by FrancoisM** [comment] 2016-03-25 09:05
Hi,

Let's rephrase in the universal language aka C# :-)

In PCL:

```
public async Task AuthenticateAsync(MobileServiceAuthenticationProvider loginProvider, string username = null,
            string password = null) => await RegisterOrAuthenticateAsync(false, username, password, loginProvider).ConfigureAwait(false);

private async Task RegisterOrAuthenticateAsync(bool isRegistration, string username, string password,
            MobileServiceAuthenticationProvider loginProvider =
                MobileServiceAuthenticationProvider.WindowsAzureActiveDirectory)
        {
            await Initialiazor.InitializeAsync();//je peux l'appeler ici car aucune autre fonction publique ne peut etre appelée en anonymous

            try
            {
                string tmp;

                if (isRegistration)
                {
                    var registrationCredentials = new LoginAndRegistrationRequest(username, password);
                    await MyLoginAndRegistrationAsync(registrationCredentials, true).ConfigureAwait(false);
                    tmp = username;
                }
                else
                {
                    switch (loginProvider)
                    {
                        case MobileServiceAuthenticationProvider.WindowsAzureActiveDirectory:
                            //I use this one for custom
                            var loginCredentials = new LoginAndRegistrationRequest(username, password);
                            await MyLoginAndRegistrationAsync(loginCredentials, false).ConfigureAwait(false);
                            tmp = username;
                            break;
                        default:
                            await Authenticator.AuthenticateAsync(MobileServiceClient, loginProvider).ConfigureAwait(false);
                            var response =
                                await
                                    MobileServiceClient.InvokeApiAsync(ApiHelper.ApiPath.RegisterExternal)
                                        .ConfigureAwait(false);
                            MobileServiceClient.CurrentUser.UserId = (string) response["UserId"];
                            tmp = (string) response[loginProvider.ToString()]["name"];
                            break;
                    }
                }

                User = new LoggedUser(MobileServiceClient.CurrentUser.MobileServiceAuthenticationToken, MobileServiceClient.CurrentUser.UserId, tmp);
                IsAuthenticated = true;
            }
            catch (Exception ex)
            {
                MobileServiceClient.CurrentUser = null;
                User = new LoggedUser();
                IsAuthenticated = false;
                if (ApiHelper.IsApiError(ex.Message))
                    throw new ApiException(ex.Message, ex);
                throw;
            }
        }

private async Task MyLoginAndRegistrationAsync(LoginAndRegistrationRequest userCredentials, bool isRegistration)
        {
            var controller = (isRegistration ? ApiHelper.ApiPath.Register : ApiHelper.ApiPath.Login).Replace("api/", string.Empty);//invokeapi vca le rajouter
            var authToken =
                    await
                        MobileServiceClient.InvokeApiAsync(controller, JObject.FromObject(userCredentials))
                            .ConfigureAwait(false);
            MobileServiceClient.CurrentUser = new MobileServiceUser((string) authToken["user"]["userId"])
            {
                MobileServiceAuthenticationToken = (string) authToken[LoginAsyncAuthenticationTokenKey]
            };
        }
```

In each platforms:

`public async Task<MobileServiceUser> AuthenticateAsync(IMobileServiceClient mobileServiceClient, MobileServiceAuthenticationProvider loginProvider) => await mobileServiceClient.LoginAsync(UIApplication.SharedApplication.KeyWindow.RootViewController, loginProvider);`

Note that I don't use WindowsAzureActiveDirectory, I just use that enum for custom authentication. And this is where my issue is. Not with Facebook.
I have to call MyLoginAndRegistrationAsync for custom login rather than Authenticator.AuthenticateAsync as the LoginAsync function was missing ZUMO-API-VERSION as in the mobile service code it calls client.HttpClient.RequestWithoutHandlersAsyn.

I hope the issue is better illustrated now.

**Comment by adrianhall** [comment] 2016-03-25 18:27
Illustrated.  Put more succinctly:

"I wish to use LoginAsync() to perform custom authentication actions where the action is embedded in my code base rather than using the Authentication / Authorization service provided by Azure App Service"

**Comment by lindydonna** [comment] 2016-05-04 17:39
@mattchenderson Could you review and decide whether this is a won't-fix?

**Comment by lunjio** [comment] 2016-05-10 19:35
hi, I would like to ask help me too in similar problem, I want to override loginAsync() with my custom authentication controller, but I have a problem, I get MobileServiceInvalidOperationException  - Bad request , What I'm doing wrong ? 
api controller:
public class CustomRegistrationController : ApiController
    {

        // POST api/CustomRegistration
       // [Route("api/test/CustomRegistration", Name = "CustomRegistration")]
        public IHttpActionResult Post([FromBody] JObject registrationRequest)
        {

            JwtSecurityToken token = AppServiceLoginHandler.CreateToken(new Claim[] { new Claim(JwtRegisteredClaimNames.Sub, (string)registrationRequest["username"]) },
                "HereIsMyWebAuthKey",
                "WebsiteWithhttpsschema",
                "WebsiteWithhttpsschema",
                TimeSpan.FromHours(24));
            return Ok(new
            {
                authenticationToken = token.RawData,
                user = new { UserId = "111" }
            });
}

in configure mobile app I have added:
config.Routes.MapHttpRoute("CustomRegistration", ".auth/login/CustomRegistration", new {controller = "CustomRegistration" });     
and at last try call it from code:
var Answer = await App.MobileService.LoginAsync("CustomRegistration", registrationRequest);
where registrationRequest is custom jobject.
When I route this api controller to other custom address, I call it without problem by invokeApiAsync method. In my mobile app authentication is allowed, set to allow request, token store is on, I don't know else what to do, I tried to return in api controller "access_token" instead "authenticationToken" because somewhy in settings is shown that azure add is by default(when I saw kudu) and e.t.c, sorry for my English.

**Comment by lindydonna** [comment] 2016-07-14 21:22
@FrancoisM Can you update the issue with the exact feature that is missing from custom auth in the App Service Authentication/Authorization feature?  See https://azure.microsoft.com/en-us/documentation/articles/app-service-mobile-dotnet-backend-how-to-use-server-sdk/#custom-auth. In general, all client auth support is assumed to use this feature; if you want to authenticate a different way, you need to just use custom APIs.

**Comment by FrancoisM** [comment] 2016-07-15 07:59
Sure.
So I wanted to do custom authentication as well as authentication with providers such as Facebook.
I wanted to be consistent across these two types of authentication and only use LoginAsync so it would handle the token and so on.

There is an extension of LoginAsync with the following signature:

`public static Task<MobileServiceUser> LoginAsync(this IMobileServiceClient client, UIViewController viewController, string provider, IDictionary<string, string> parameters);`

I thought that I could use the parameter "provider" as my custom api custom authentication endpoint. So my iOS implementation looked like this:

`mobileServiceClient.LoginAsync(UIApplication.SharedApplication.KeyWindow.RootViewController, "CustomAuth", new Dictionary<string, string> { { "username", username }, { "password", password } });`

If I remember well (github does it for me lol), it did reach my endpoint. The issue though was that the header of the request generated by LoginAsync was missing ZUMO-API-VERSION.
Hence my initial post.

So here what I ended up doing:

On the client:
```
public Task AuthenticateAsync(string email, string password)
{
    var loginCredentials = JObject.FromObject(new LoginRequest(email, password));
    return MyLoginAndRegistrationAsync(loginCredentials, ".auth/CustomAuth/login");
}
```

```
private async Task MyLoginAndRegistrationAsync(JToken userCredentials, string controllerPath)
{
        var authToken = await MobileServiceClient.InvokeApiAsync(controllerPath, userCredentials).ConfigureAwait(false);
        MobileServiceClient.CurrentUser = new MobileServiceUser((string)authToken["user"]["userId"])
        {
                MobileServiceAuthenticationToken = (string)authToken[LoginAsyncAuthenticationTokenKey]
        };
}
```

On the backend:
```
[HttpPost]
[AllowAnonymous]
[Route("api/.auth/CustomAuth/login")]
public HttpResponseMessage Login(LoginRequest loginRequest)
{
    ... custom login and if ok:
    SendToken(user.Id, sid);
}
```

```
private HttpResponseMessage SendToken(string userId, string sid)
{
    var token = LoginUtils.GetAuthenticationTokenForUser(sid);
    if (token != null)
        return Request.CreateResponse(HttpStatusCode.OK, new
        {
            authenticationToken = token.RawData,
            user = new
             {
                 userId
             }
        });
        return Request.CreateResponse(HttpStatusCode.BadGateway, "No token for that userid");
}
```

```
public static JwtSecurityToken GetAuthenticationTokenForUser(string sid)
{
    var claims = new[]
    {
        new Claim(JwtRegisteredClaimNames.Sub, $"sid:{sid}"),
        new Claim("http://schemas.microsoft.com/identity/claims/identityprovider", "custom")
    };

    var token = AppServiceLoginHandler.CreateToken(
        claims,
        Startup.SigningKey,
        Startup.Audience,
        Startup.Issuer,
        TimeSpan.FromDays(30)
    );
    return token;
}
```


I hope this clarifies the initial issue and helps.

François

**Comment by lindydonna** [comment] 2016-07-15 21:56
So, are you saying that you wanted ZUMO-API-VERSION to be included in the call to your custom login endpoint?  Note that the header is only required for custom APIs that have the attribute [MobileAppController]. Since your login controller does not look like it's a general API controller that would be called as a custom API, you should just leave off this attribute, and there will be no check for the ZUMO-API-VERSION header.

**Comment by FrancoisM** [comment] 2016-07-16 05:31
Thanks @lindydonna that explains it! I was using the [MobileAppController] attribute by mimicry because I saw it everywhere without knowing what it means or does.

**Comment by lindydonna** [comment] 2016-07-18 19:49
Closing this issue, as it was caused by using the [MobileAppController] attribute on the custom auth API controller.

**Closed by lindydonna** 2016-07-18 19:49 UTC
Labels: Area-Authentication, Feature Request
