### ISSUE TITLE
MobileServiceAuthenticationProvider Runtime Error on New Xam.Forms Project and 3rd Party Auth

### ISSUE THREAD

**Issue by dgerding** [Azure/azure-mobile-apps-net-client#401] opened 2017-12-27 22:19 UTC
Hi,
I'm using the most recent release VS on Windows and the most recent Xamarin Forms template with a .net standard 2 Xam forms project.  When I try and add authentication like here:

https://docs.microsoft.com/en-us/azure/app-service-mobile/app-service-mobile-xamarin-forms-get-started-users

I've added both Facebook and Microsoft authentication so far and get the same runtime exception in my Android project when the following line executes:

```
App.User = await App.MobileServiceClient.LoginAsync(this,
                    MobileServiceAuthenticationProvider.MicrosoftAccount, "wordbahn");

```                
I get the following exception which seems related to the Compatibility plugins for Android Xamarin.
```

Unhandled Exception:

Java.Lang.NoSuchMethodError: No static method startActivity(Landroid/app/Activity;Landroid/content/Intent;Landroid/os/Bundle;)V in class Landroid/support/v4/app/ActivityCompat; or its super classes (declaration of 'android.support.v4.app.ActivityCompat' appears in /data/app/com.wordbahn.app.android-oy5ciYyYhTv6fDeVW0RooQ==/base.apk) occurred
```

**Comment by rubenmamo** [comment] 2018-01-03 14:35
I also get this same issue. I only managed to get authentication to work if I use an older version of the Xamarin.Forms library (v 2.4.0.282) and V23.3.0 of Xamarin.Android.Support.Design, Xamarin.Android.v7.AppCompat, Xamarin.Android.Support.v4 and Xamarin.Android.Support.v7.CardView.

As soon as you load later versions the error mentioned above starts appearing.

Unfortunately this means that I cannot use authentication and some of the later plugins such as https://github.com/jamesmontemagno/GeolocatorPlugin which requires a later version of the above mentioned libraries

**Comment by LorenK96** [comment] 2018-01-03 21:37
Having the same issue, packages for my Portable solution:
- Microsoft.Azure.Mobile.Client (v4.0.2)
- NETStandard.Library (v2.0.0)
- Xamarin.Forms (v2.5.0.121934)

Packages for my Android solution:
- Xamarin.Forms (v2.5.0.121934)
- Xamarin.Android.Support.Design (v23.3.0)
- Xamarin.Android.Support.Support.v4 (v23.3.0) 
- Xamarin.Android.Support.v7.AppCompat (v23.3.0)
- Xamarin.Android.Support.v7.CardView (v23.3.0)
- Xamarin.Android.Support.v7.MediaRouter (v23.3.0)

First the docs aren't up to date, now this. Microsoft, should we be using your services or not?

**Comment by rubenmamo** [comment] 2018-01-05 08:17
@LorenK96 np. 
Unfortunately the downgrade makes a number of plugins unusable and the tooling doesn't provide you with any information why this is happening. What I've found out is that some of the Xamarin Plugin Nuget packages you install them, everything builds correctly and then you just get random errors.
I find development with Xamarin to be a complete nightmare compared to what we're used within the .Net world.

**Comment by LorenK96** [comment] 2018-01-05 22:15
@rubenmamo Yeah, I've found it way too unstable to use, even with the downgrade. I'll be tossing the whole stack out and likely using something like React Native + Firebase instead.

**Comment by bmourat** [comment] 2018-01-09 13:01
Hey all!
The problem is that Xamarin.Auth, which is used underhood is using one version of Xamarin.Android.Support.CustomTabs library which is v25.3.1 and you are using support libraries of version v26.1.0.1 which are not compatible with each other. So to fix this problem you can add Xamarin.Android.Support.CustomTabs library to packages for the Android solution with a version that corresponds to other support libraries. All support libraries must have one version.
In case of @LorenK96 it should be:
```
"Xamarin.Android.Support.CustomTabs": "26.1.0.1"
```

**Comment by ciani** [comment] 2018-01-12 12:42
Hi @bmourat and thanks for the solution

In my case I need to install the 25.4.0 version, but it is works :)

**Comment by ltaljaard** [comment] 2018-02-14 10:44
Thanks @bmourat that worked for me. Microsoft should really fix this so it works out of the box.

**Comment by elamalani** [comment] 2018-03-05 20:39
Closing this issue as the error can be resolved by the suggestion shared by @bmourat.

**Closed by elamalani** 2018-03-05 20:39 UTC
