### ISSUE TITLE
CreatedAt/UpdatedAt values truncated before reaching server

### ISSUE THREAD

**Issue by gonzobrains** [Azure/azure-mobile-apps-net-client#466] opened 2018-10-17 18:18 UTC
Hi Azure Team,

I have a sync problem that I think is related to timestamps being truncated.  Our syncs take an unusually long amount of time, which may be because the client-side timestamps are being truncated, causing the queried time to always be less than the time for each record listed on the server.

In order to make this easily reproducible, please download the Azure "to do" quickstart and look at the table for to-do items on the server.  Our copy shows that CreatedAt and UpdatedAt columns use the  [datetimeoffset](7) datatype (see attached).

However, our server logs show the GET requests only going out to three digits of fractional second precision (see attached).  Since these properties are not part of the object model, I can only assume the truncation is occurring in the Azure mobile apps net client.

Could you please take a look at this and confirm whether or not the Azure sync client is causing this?  Is there a workaround available?

Thanks,
Jeff

![server_data_not_truncated](https://user-images.githubusercontent.com/364198/47107480-6ecfe800-d217-11e8-9c2b-05aeafe85c4d.PNG)

![datetimeoffset_truncated](https://user-images.githubusercontent.com/364198/47107367-27e1f280-d217-11e8-9b64-2a73658750f0.PNG)

![todoitem_table2](https://user-images.githubusercontent.com/364198/47107007-164c1b00-d216-11e8-8656-702a3b990c80.PNG)

**Comment by gonzobrains** [comment] 2018-10-19 12:15
Could I set the precision of the SQL datatype to match the truncated one?
If not, will I run in to problems with the service always returning too
many values to my client app?

**Comment by gonzobrains** [comment] 2018-10-19 12:37
In the hundreds per table.  Also, can I use a query to limit the amount of
table data downloaded to the client app?  Users don't need to work with the
entire database (which wouldn't fit anyway), just a few weeks worth of data.

**Comment by MatkovIvan** [comment] 2018-10-19 13:44
> Also, can I use a query to limit the amount of table data downloaded to the client app?  Users don't need to work with the entire database (which wouldn't fit anyway), just a few weeks worth of data.

[How to: Filter returned data](https://docs.microsoft.com/en-us/azure/app-service-mobile/app-service-mobile-dotnet-how-to-use-client-library#filtering)
[How to: Return data in pages](https://docs.microsoft.com/en-us/azure/app-service-mobile/app-service-mobile-dotnet-how-to-use-client-library#paging)

**Comment by gonzobrains** [comment] 2018-10-24 17:52
The Azure support team is looking into this.  Allow me to clarify something:  we don't have hundreds of entries that get updated within milliseconds.  We would rarely have conflicts either because users never work on other users' data.  What I am suggesting here is that perhaps when we call PullAsync() on a table with a lot of data that we would get updates of the same data on every sync because the truncated value on the client is always comparing to the actual value in the server which is always later due to the extra milliseconds in the non-truncated original value.

Does that make sense?  Thanks.

**Comment by MatkovIvan** [comment] 2018-10-25 10:14
> we would get updates of the same data on every sync because the truncated value

In fact, the reason is not even that.
Incremental sync feature uses the filter by `updatedAt` value as **greater or equal** than you already have on the device. So, it's OK that you get the last record each time. This is by design.

Related topics: https://github.com/Azure/azure-mobile-apps-net-client/issues/395, https://github.com/Azure/azure-mobile-apps-ios-client/issues/177, https://github.com/Azure/azure-mobile-apps-net-server/issues/241

I close this issue because it's expected behavior of SDK.

**Closed by MatkovIvan** 2018-10-25 10:14 UTC
