### ISSUE TITLE
__includeDeleted = true is always appended to the query created by .NET SDK

### ISSUE THREAD

**Issue by mintyfusion** [Azure/azure-mobile-apps-net-client#520] opened 2019-11-03 23:00 UTC
This issue was raised here: https://github.com/Azure/azure-mobile-apps-net-client/issues/355 where __includeDeleted = true is being appended automatically.

We would like to control which records are returned and not always want to have __includeDeleted = true and their is no way to override this property.

Use Case:

1) If the device is being synced first time, we would like to not get any Deleted records and which we can query on our side to find out if Database has records for that specific table or not and make appropriate decisions.

2) If no records are found, we would like to turn off the __includeDeleted. If records found, then query can perform as is, because we will treat it as incremental sync and data may have been soft deleted at other places, and would need to be synced to get that update.

Is there a way to do it right now?

**Comment by MatkovIvan** [comment] 2019-11-05 13:34
Hi @mintyfusion ,

Currently the SDK doesn't provide a way to control this parameter during first sync. I've just checked behaviour of client SDK for other platforms - it's the same there. So, it isn't a bug of .NET SDK - it's by design. This issue is more like an improvement / feature request.

Unfortunately, [the product team is not currently investing in any new feature work for Azure Mobile Apps](https://github.com/Azure/azure-mobile-apps-net-client#future-of-azure-mobile-apps), so I'm closing this. Please note that the SDK is fully open source, so you can change it to suit your needs.

**Closed** 2019-11-05 13:34 UTC
Labels: Feature Request
