### ISSUE TITLE
Use MobileServiceSQLiteStore with SQLitePCLRaw.bundle_zetetic 

### ISSUE THREAD

**Issue by garett** [Azure/azure-mobile-apps-net-client#560] opened 2021-01-13 22:46 UTC
We use SQLCipher on several projects. We are in the process of upgrading to the latest version, along with the mobile apps client. Is it possible to get the current mobile app client to work with SQLitePCLRaw.bundle_zetetic? In the past we wrote our own custom MobileServiceSQLiteStore that worked with SQLCipher. Just wondering if there is any way to use the existing MobileServiceSQLiteStore.

**Comment by adrianhall** [comment] 2021-05-20 18:27
No - you will have to write a duplicate of the MobileServiceSQLiteStore with your adjusted libraries.

**Closed by adrianhall** 2021-05-20 18:27 UTC

**Comment by angelrishi** [comment] 2021-12-19 11:54
Dear @garett, I need your help and I am looking for the similar solution. 
Please message me as I also want to implement SQLCipher with AzureMobile Offline sync in Xamarin.Forms. Any help will be highly appreciated. Thank you.Could you share the localstore version of MobileServiceSQLiteStore that can be used with sqlcipher?

**Comment by garett** [comment] 2021-12-28 16:12
Hi @angelrishi. We initially implemented a duplicate of the MobileServiceSQLiteStore specifically for SQLCipher. It has been working fine for a couple years now. We've since refactored it based on the most recent changes to SQLCipher. This latest version is much simpler. I can share the class we implemented with you.

**Comment by angelrishi** [comment] 2022-01-04 18:44
Dear Garett, I am immensely happy to hear from you. Apologies for the delay in my reply. I will be very grateful if you can help with the SQLCipher class. Thank you. Angel

**Comment by angelrishi** [comment] 2022-01-16 10:03
> 

Waiting for your help :) Thank you so much. :)

**Comment by garett** [comment] 2022-01-18 13:15
Hi @angelrishi. I implemented two versions. The first was a complete duplicate of the MobileServiceSQLiteStore with changes specifically to support SQLCipher. However, with the most recent versions of SQLCipher I no longer needed to do that. You can just subclass the MobileServiceSQLiteStore. Below is what I did. I hope this helps.

public class SQLCipherMobileServiceStore : MobileServiceSQLiteStore
    {
	   protected SQLCipherMobileServiceStore() { }

	   public SQLCipherMobileServiceStore(string databasePath, string password, string licenseKey = null) :
		  base(databasePath)
	   {
		  this.ExecuteNonQueryInternal($"PRAGMA key = '{password}';", null);

		  if (!string.IsNullOrEmpty(licenseKey))
		  {
			 this.ExecuteNonQueryInternal($"PRAGMA cipher_license = '{licenseKey}';", null);
		  }
	   }
    }

**Comment by angelrishi** [comment] 2022-01-18 13:22
@garett, Thank you so much. The idea of inheriting from MobileServiceSQLiteStore sounds great!
I will try this out. I am currently making the SEE work with the latest MobileServiceSQLiteStore. Also, will try SQLCipher.

**Comment by angelrishi** [comment] 2022-01-23 18:13
Dear @garett, I just want to say a BIG THANK YOU to you. Thank you so much for caring for the fellow programmer :). The solution of yours worked very nicely.
Best Wishes, Angel
