### ISSUE TITLE
Library does not work in .NET Core 2.1

### ISSUE THREAD

**Issue by StefH** [Azure/azure-mobile-apps-net-client#467] opened 2018-10-18 09:05 UTC
I create a .NET Core 2.1 console app and followed the examples at:

- https://docs.microsoft.com/en-us/azure/app-service-mobile/app-service-mobile-windows-store-dotnet-get-started
- https://docs.microsoft.com/en-us/azure/app-service-mobile/app-service-mobile-dotnet-how-to-use-client-library

My code is:
``` c#
var client = new MobileServiceClient(MobileAppUrl);

// Create a typed table reference
IMobileServiceTable<TodoItem> todoTable = client.GetTable<TodoItem>();

// TODO : this fails on NETCore 2.1 ?

// This query filters out completed TodoItems
// http://***.azurewebsites.net/tables/TodoItem?$filter=not(complete)
List<TodoItem> items = await todoTable.Where(todoItem => !todoItem.Complete).ToListAsync();
Console.WriteLine($"item count = {items.Count}");
foreach (var item in items)
{
    Console.WriteLine($"{item.Text}");
}
```

However I get an exception:

> The server did not provide a response with the expected content.

This [StackOverflow Issue](https://stackoverflow.com/questions/51483518/azure-mobile-backend-connection-issue-on-asp-net-core-2-1) also defined this problem.

Problem is in this code:
https://github.com/Azure/azure-mobile-apps-net-client/blob/70d79ce835881d62a8a5a9399aa1175f1457bd85/src/Microsoft.Azure.Mobile.Client/Http/MobileServiceHttpClient.cs#L620

Could it be that gzip response compression is not handled by .NET Core 2.1 ???

Response in fiddler looks like:
```
HTTP/1.1 200 OK
Cache-Control: no-cache
Pragma: no-cache
Content-Length: 326
Content-Type: application/json; charset=utf-8
Content-Encoding: gzip
Expires: 0
Vary: Accept-Encoding
Server: Microsoft-IIS/10.0
X-Powered-By: ASP.NET
Set-Cookie: ARRAffinity=317fc761243dff568147bab1a7c8eb4e658734b4a4080b4361c90b19a1fcc566;Path=/;HttpOnly;Domain=***.azurewebsites.net
Date: Thu, 18 Oct 2018 08:55:40 GMT

         `I %&/m {J J  t  `$ؐ@      iG#) *  eVe]f@ 흼  {   {   ; N'   ?\fdl  J ɞ!   ?~|?"   ?  e 泏 ge  >Z f } ~ 製 

*** FIDDLER: RawDisplay truncated at 128 characters. Right-click to disable truncation. ***
```

**Comment by elamalani** [comment] 2018-10-18 18:21
@StefH We don't support .NET Core 2.1 in the Azure Mobile Apps SDK. We are not doing active development in the product, so we won't add any new features. I will close the issue for now but feel free to contact us if you have any questions.

**Closed by elamalani** 2018-10-18 18:21 UTC

**Comment by StefH** [comment] 2018-10-18 19:51
Thanks for the information. Can you tell which new project will have this functionality?

**Comment by elamalani** [comment] 2018-10-18 20:43
We are in the very early stages of customer research to design the new services, so it's too soon to say what product would be the new home for these services.

Please stay tuned with updates on our documentation and readme. We will share more information when we are ready.

**Comment by JohnPenney** [comment] 2018-10-19 08:51
@elamalani - do you have any understanding of why a change from .NET Core 2.0 to .NET Core 2.1 would cause gzip response compression to fail in Azure Mobile Apps?   If you could give us any kind of clue as to what went wrong, then maybe we could seek a workaround?

**Comment by ElektrojungeMS** [comment] 2018-10-19 23:44
Hi @JohnPenney,

As @elamalani pointed out above, we don't support .Net Core 2.1 in the SDK today. Unfortunately, we don't have a workaround today and like Ela said, the we don't have an ETA for a new release or other SDK to use for .Net Core 2.1 compatibility yet, so your only workaround is to stick with .Net Core 2.0 for now.

**Comment by guillermoeuillades** [comment] 2019-09-28 19:55
the issue is now here with some workarrounds. 
https://github.com/Azure/azure-mobile-apps-net-client/issues/514
