### ISSUE TITLE
MobileServiceSQLiteStoreExtensions.cs: "The generic type T does not have parameterless constructor."

### ISSUE THREAD

**Issue by dgerding** [Azure/azure-mobile-apps-net-client#371] opened 2017-07-25 15:47 UTC
Hi,
I'm getting a runtime exception throw by MobileServiceSQLiteStoreExtensions.cs (line 38).  The exception is ArgumentException("The generic type T does not have parameterless constructor.").

It's raised when I call Db.DefineTable<t_ypeName_> during app startup.

I can't figure why the error is thrown for some types of my types but not others when *none* of my types have parameterless constructors and they just have simple string and int properties.

**More importantly, can anyone tell me the right workaround or contract initialization that might prevent the error?  Still googling, but figured I'd start here.**

Thanks!
Dave Gerding

**Comment by dgerding** [comment] 2017-07-28 00:10
Hi Again, I can confirm the even stranger condition which is this exception is only raised when I run the code on a real iOS device.  On the iOS simulator the code runs just fine.

**Comment by dgerding** [comment] 2017-07-28 00:24
Additional information: It seems to influenced by the number of types I try and add to Db using the DefineTable call.  The third call to DefineTable throws the error.  It's not the types themselves because if I move a type that throws the exception to the top of the list, it starts working.

...

**Comment by dhei** [comment] 2017-10-09 21:38
Looks like something already resolved by the original poster.

**Closed by dhei** 2017-10-09 21:38 UTC

**Comment by guillermoeuillades** [comment] 2019-10-08 20:08
I had the same issue. The issue is that the DefaultContractResolver from Newtonsoft.Json cant read correctly the Default Creator. It was solved by change the linker to "Link only SDK assemblies"
