### ISSUE TITLE
.PullAsync(queryId, query) does not pull effectively after .PurgeAsync()

### ISSUE THREAD

**Issue by PaulARoy** [Azure/azure-mobile-apps-net-client#24] opened 2015-12-04 09:17 UTC
Hi,

I'm having a little trouble here, I'm not sure if it's how it's supposed to work but on the previous beta release I never experienced this issue.

When my user logs I pull all the entries for this user with `mytable.PullAsync(queryIdForUser, mytable.CreateQuery())`. When he disconnects, I purge all the data with `myTable.PurgeAsync()`

But if he reconnects again (after a purge), only one entry is downloaded with `mytable.PullAsync(queryIdForUser, mytable.CreateQuery())`. I expect the framework to download everything.

The workaround I use is to take null as queryId, but I'm loosing the incremental download.

Is this the expected behavior?

PS: I'm using SQLiteStore, and on back-end `.GetAll()` only fetch the user data.

**Comment by phvannor** [comment] 2015-12-04 17:40
No behavior change was intended here, as long as you pass the queryId to purge it should reset it, so the next call using that Id should be identical to the initial one

(see: https://github.com/phvannor/azure-mobile-apps-net-client/blob/master/sdk/src/Microsoft.WindowsAzure.MobileServices/Table/Sync/Queue/Actions/PurgeAction.cs#L69)

Its possible some oddness could be caused if you don't have the same server-client bits post the last breaking change on column names (__updatedAt -> updatedAt) as that could cause the query to try to use the wrong data/etc.  Can you confirm your server & client models are using the new names (no __)

**Comment by PaulAchess** [comment] 2015-12-09 08:58
I checked, the column names are okay.

When I purge with the queryId, everything works fine, thank you very much for you advice!

However, `PullAsync(queryId)` + `PurgeAsync()` (no parameter) + `PullAsync(queryId)` seems to take one entry only. I was working with the latest beta version (2.0.0-beta3), maybe I should try with the 2.0.0. I'll take a shot whenever I have the time.

This behavior was not the same before, I understand it's a bit out of the process, but I think there's probably something to investigate.

**Comment by rossjempson** [comment] 2016-01-07 00:57
I've noticed identical behaviour.  PurgeAsync followed by PullAsync only pulls one record (but my test table only has 2 records, so it may be that it just doesn't pull all).

I think it is a valid use case.  I have a scenario where users share a device, it is allocated to a vehicle, and it needs to work offline.  Each time a user logs in they are forced to choose a vehicle, and I then synchronize the users table but filter it to only return users that are allocated to the selected vehicle.  The point being that the next time someone needs to work offline, the users table is reasonably up to date with the valid users for that vehicle.

I've noticed that the results of the query on the server returns all rows, so I suspect it is the query string being applied via IQueryable that is causing the problem.  I am thinking of either massaging the data (updatedAt I suspect) on the server side to trick the query string to work, or I may just create a separate database locally on the client and manually keep it up to date.  The client will never modify the user table's data, so I don't need to synchronize changes.

**Comment by phvannor** [comment] 2016-01-07 01:05
Yes PurgeAsync() [no query id] does not clean up the updatedAt meta data tracked by the client.  So the next PullAsync(QueryId) will continue from where it left off, meaning you won't get any purged records.  

We'd need to provide a purgeAsync() that lets you clear ALL queryId caches.  In the meantime you must call PurgeAsync with a QueryId for the initial updatedAt query to say 1970 and not where it left off.

**Comment by rossjempson** [comment] 2016-01-07 01:10
Thanks for that.  I'm not sure what you mean by "call PurgeAsync with a QueryId for the initial updatedAt query "?  I don't see any parameters to PurgeAsync()?

**Comment by phvannor** [comment] 2016-01-07 01:16
Should be, here's the definition: https://github.com/Azure/azure-mobile-apps-net-client/blob/master/sdk/src/Microsoft.WindowsAzure.MobileServices/Table/Sync/IMobileServiceSyncTable.cs#L126

**Comment by rossjempson** [comment] 2016-01-07 01:19
Sorry, my mistake.  I'm going to blame intellisense.  I'll try it out.

**Comment by rossjempson** [comment] 2016-01-07 11:53
As recommended above, calling PurgeAsync with the same queryid / query as the original pull fixes this problem.

**Comment by PaulAchess** [comment] 2016-01-07 13:00
:+1: 

Could this be flagged as an enhancement? (or bug?)

I really think `PurgeAsync()` without parameter should purge every queryId.

**Comment by phvannor** [comment] 2016-01-07 17:38
It will be a breaking change to flip to purging QueryIds.  The other use of purgeAsync not mentioned in this thread is for expiring data.  Say you wanted your cache to contain only records made w/in the last 60 days, or only unresolved incidents, etc.  In those types of cases, you don't want the purge to clear the inc sync key.  Flipping the default would break people using Purge for those types of flows.

But having an override that PurgesAndClearsAllKeys() would be good to have.

**Comment by PaulAchess** [comment] 2016-01-07 19:33
I understand but it was already a breaking change when it stopped working this way. 

I was using PurgeAsync() to clean my data with the preview, it worked and it made sense at the time. This is why I opened this bug: a breaking change into the existing. 

The actual PullAsync(query) + PurgeAsync() has some really messed up consequences right now. I should not have only one entry pulled, it just does not make sense (even if it can be and has been explained). 

A new name could simply be PurgeAllAsync().

**Comment by phvannor** [comment] 2016-01-07 20:08
I'd need to run some tests I can't figure out how this could have changed.  The first commit introducing incremental sync to managed (https://github.com/Azure/azure-mobile-services/blob/9cd07b53c5d4a677516a0dd4fb5863e7dd64d008/sdk/Managed/src/Microsoft.WindowsAzure.MobileServices/Table/Sync/Queue/Actions/PurgeAction.cs) shows the delta token is only reset if a query key was passed in.  

From what I can tell out of the history, this behavior has not changed since we introduced it.  

In iOS, I have the force flag kill all DeltaTokens, but it appears in Managed, force doesn't work the same way.  Some love is needed on this API to clarify the various workflows intended and what should be used when.

**Comment by PaulAchess** [comment] 2016-01-08 07:52
I can guarantee it has changed, as it was a basic use case for us (user logs out -> PurgeAsync(), user logs in -> PullAsync(query)) which was working before the update. Could it be a change in the server? I have updated both server and client at the same time. Or from the Pull, maybe along with 519fadb62beed40dcfb161ba05dc71a8b8fd1038?

Now it was on a preview version so I really think we should not bother about wether it has changed or not (we know how it works and what it does which is really enough).

On the other hand I really think the actual system is counter-intuitive, even if it makes sense at a lower level.

**Comment by rossjempson** [comment] 2016-01-08 10:30
Maybe a compromise would be to change PurgeAsync() to PurgeAsync(bool purgeAllKeys = false) which would preserve the current behaviour but give new consumers the option and insight into what is happening.

**Comment by PaulAchess** [comment] 2016-01-08 10:46
That would be nice!

**Comment by renzska** [comment] 2016-02-03 17:37
I experienced the same issue here where different users would log out and a new user would login. The new user wouldn't get any data. My filtering is done on the server side so the queryId is the same for all users. Is there a potential date for when this will be added? My first impression of PurgeAsync() was that it would allow me to clear the database tables I specified.

**Comment by rossjempson** [comment] 2016-02-03 23:23
The way I have approached it is two fold.  Firstly, I name queryids to match the server side filtering logic, so if the server side filters by UserId, I include the Userid in the queryid to ensure it is always unique, and therefore can purge accordingly /  accurately.

The second thing I've done, to address this problem plus some other complexities, is I create a different local database name based on the users login name.  So if John.Doe logs in and Jane.Doe logs in, there will be two local databases, "John.Doe.db" and "Jane.Doe.db".  This approached simplified things a lot for me.  It will result in slight inefficiencies sometimes, for example one user won't get the benefit of the other user having already refreshed some reference data lets say, but for me it was worth the trade-off.

**Comment by lindydonna** [comment] 2016-05-04 17:47
I'm closing this as won't-fix, because it will be a breaking change to purge all query IDs.

**Closed by lindydonna** 2016-05-04 17:47 UTC
Labels: Feature Request

**Comment by DanielCauser** [comment] 2017-03-03 04:05
Hey everyone, I had the same issue.Putting the same query id for the pull and for the purge fixed the problem.
