### ISSUE TITLE
Xamarin iOS Safari Credentials Autofill Failure

### ISSUE THREAD

**Issue by rumbltravel** [Azure/azure-mobile-apps-net-client#536] opened 2020-04-28 18:54 UTC
After calling MobileServiceClient.LoginAsync(...) the SFSafariViewController gives the option to use Safari autofill credentials for social auth. If a user utilizes the autofill functionality the WebView closes before auth is complete and the LoginAsync(...) call is never returned.

**Comment by AnastasiaKubova** [comment] 2020-04-29 05:49
Hi, @rumbltravel ! Thanks for getting in touch with us!
Could you please share the more details: 
- what version of SDK are you use?
- on the what platform it happens?
- verbose logs

**Comment by rumbltravel** [comment] 2020-05-04 20:40
SDK Version: 4.1.2
Platform: iOS
Logs Attached
[DeviceLog_AutofillSignIn.txt](https://github.com/Azure/azure-mobile-apps-net-client/files/4577296/DeviceLog_AutofillSignIn.txt)

**Comment by Jamminroot** [comment] 2020-05-05 15:31
Hey, @rumbltravel, thanks for sharing this info.
Please let me some time to investigate what's going on with the SDK.

**Comment by rumbltravel** [comment] 2020-05-05 15:33
Great, thanks! It’s definitely something that needs to be fixed as soon as possible because people are struggling to sign in, which isn’t good!

Thanks for the help on this!

Luke E. Reber
Chief Executive Officer | RUMBL
620.755.6652
Luke.reber@rumbltravel.com
________________________________

**Comment by rumbltravel** [comment] 2020-05-06 14:43
Hey @Jamminroot 

Whats the status on this? Making any progress on this?

Thanks!

**Comment by Jamminroot** [comment] 2020-05-06 15:00
Yup, deployed test environment for this one. Currently investigating and and discussing this with colleagues. I'll update you on the progress

**Comment by rumbltravel** [comment] 2020-05-06 16:10
Awesome, thank you!

**Comment by Jamminroot** [comment] 2020-05-07 10:56
@rumbltravel, we've tested it - and unfortunately couldn't reproduce locally. I wanted to ask for more details on this one:
Is there a chance for you to check whether it occurs on fresh sample project (for example, you can use our [quickstarts repo](https://github.com/Azure/azure-mobile-apps-quickstarts))?
If it is reproduced - can you update us with detailed step-by-step guide?

**Comment by rumbltravel** [comment] 2020-05-07 20:47
@Jamminroot This just got a lot more interesting. I tried to create a barebones app that uses our auth logic, and when I add my autofill credentials to the iOS simulator and login, it works flawlessly. I tried it with our app and that worked in the simulator as well, but it still fails on an actual phone. Both my phone and the simulator are running iOS 13.4.1.

**Comment by Jamminroot** [comment] 2020-05-08 10:12
That is quite odd, yes... That explains why it won't reproduce locally.
Ok. is there a chance to check if something is interfering with the web view flow in tour project?

**Comment by rumbltravel** [comment] 2020-05-08 19:54
@Jamminroot not that I can tell, the app waits on the LoginAsync(...) call to be returned but it never is, the web view just closes and the login function never returns. 

The interesting part is if you try to login again the app does nothing, almost as if the MobileServiceClient knows it's still in the middle of authenticating but the web view is not visible.

**Comment by russelarms** [comment] 2020-05-14 11:35
>This just got a lot more interesting. I tried to create a barebones app that uses our auth logic, and >when I add my autofill credentials to the iOS simulator and login, it works flawlessly. I tried it with >our app and that worked in the simulator as well, but it still fails on an actual phone. Both my >phone and the simulator are running iOS 13.4.1.

Hi, does the barebones app also fail on the actual phone?

**Comment by rumbltravel** [comment] 2020-05-16 20:38
@russelarms @Jamminroot I didn't have a chance to try it. However, I did some more testing and I seem to have figured out a workaround. For some reason when the web auth runs on an actual phone and the web page moves to the next, the app calls OnResume(). We had logic to change the page when OnResume() was called in case something was missing and after taking that out the autofill works.

**Comment by MatkovIvan** [comment] 2020-05-18 07:54
Glad that the problem has been resolved. I'm closing this issue now, but feel free to reply here if you have more questions

**Closed by MatkovIvan** 2020-05-18 07:54 UTC
