### ISSUE TITLE
Platform-specific MobileServiceClientExtensions for Android aren't available

### ISSUE THREAD

**Issue by BioTurboNick** [Azure/azure-mobile-apps-net-client#361] opened 2017-07-07 02:23 UTC
I've tried both in my Xamarin.Forms project and a fresh Xamarin.Android project. Added Microsoft.Azure.Mobile.Client v4.0.0, MobileServiceClientExtension class is present, but it only contains the common LoginWithMicrosoftAccountAsync(...) method.

UWP and iOS projects have fully populated MobileServiceClientExtension methods.

**Comment by BioTurboNick** [comment] 2017-07-07 02:32
Noted: XML files in the Nuget package have documentation for extension methods in uap10.0, xamarinios10, and in monoandroid71, but none in netstandard1.4, net45

**Comment by BioTurboNick** [comment] 2017-07-07 02:34
Aha! It's using the netstandard DLL, not the monoandroid71 DLL.

**Comment by BioTurboNick** [comment] 2017-07-07 03:16
Removing the reference and adding the correct one fixed that error, but introduced another one. When I try to build with the new reference, I get a FileNotFoundException while loading assembly Xamarin.Android.Support.CustomTabs

**Comment by BioTurboNick** [comment] 2017-07-07 03:44
Hmm, I seem to be going down some dependency rabbit hole. I found Xamarin.Android.Support.CustomTabs in Nuget and installed it. Now it's looking for "PCLCrypto", which I grabbed. Now it's building without errors.

**Comment by BioTurboNick** [comment] 2017-07-07 07:24
It builds, but I'm getting an unhandled exception with no data somewhere in the LoginAsync call, deep in the code. But no idea if it's related or not. The call stack at the time of this exception is:
 	0xFFFFFFFFFFFFFFFF in System.Diagnostics.Debugger.Mono_UnhandledException_internal	C#
 	0x1 in System.Diagnostics.Debugger.Mono_UnhandledException	C#
 	0x26 in object.17e5c9c5-2ed0-4805-a5c7-4ae8e9156107	C#
 	0xBB in Xamarin.Auth._MobileServices.WebAuthenticatorNativeBrowserActivity.OnCreate	C#
 	0x11 in Android.App.Activity.n_OnCreate_Landroid_os_Bundle_	C#
 	0x17 in object.17e5c9c5-2ed0-4805-a5c7-4ae8e9156107	C#

**Comment by BioTurboNick** [comment] 2017-07-08 19:50
In theory, that last is because it requires API level 25 and up for that method to exist, but I'm running it on an Android 7.1 - API 25 emulator, with 25.3.1 Xamarin.Android.Support.CustomTabs library (method does exist when reference is examined in Object Browser). But... looks like this library is being built with 23.3.1 of Xamarin.Android.Support.CustomTabs.

**Comment by BioTurboNick** [comment] 2017-07-08 20:52
Building the library with CustomTabs 25.3.1 works. I can now log in on Android, even on an emulator with lower API level (23 in this case).

**Comment by BioTurboNick** [comment] 2017-07-08 22:39
Note: With 4.0.1 release, dependencies changed from MonoAndroid 7.1 --> 7.0, and CustomTabs 25.3 --> 23.3.

With my Android project at API level 25 (Xamarin defaults to 23) with matching Xamarin.Android.Support v25 NuGet packages, the 4.0.0 release works on an API level 25 emulator, but 4.0.1 does not (MissingMethodException). On an API level 23 emulator, a NullReferenceException occurs in RedirectUrlActivity.OnCreate(), though perhaps that's expected.

**Comment by BioTurboNick** [comment] 2017-07-09 06:26
Linked to #348, #349

**Comment by BioTurboNick** [comment] 2017-07-10 02:42
On physical API level 23 (Android 6.0.1) device (Galaxy On5) with app built with v25 Xamarin.Android libraries, v4.0.0 Azure.Mobile.Client library, login works, though is affected by the failure to close the custom tabs discussed in #341.

**Comment by ericbrunner** [comment] 2017-07-10 12:17
@BioTurboNick Either all of the SDK developer are offline or on vacation. I can see that you as me , too don't get any answer recently. 

However I try to help: I guess you ran into the same secanrio like me 

**Solution after updated to v.4.0.0:**

Target your Xamarin.Forms Droid .csproj to Android **7.1** 

See my issue [#352](https://github.com/Azure/azure-mobile-apps-net-client/issues/352)

**Comment by MatkovIvan** [comment] 2017-07-12 13:42
Hi @BioTurboNick! Thanks for keep in touch.
I tried to reproduce this issue on next configuration (as I understand, your problem is on same configuration):
- SDK 4.0.1;
- Support libraries 23.3.0;
- Project target API 25;
- Emulator with android 6.0 (API 23)

and it show login fine. Other tested configurations works as well.
Could you please clarify reproduction steps or may be you have some broken sample project?

**Comment by KlausLoeffelmann** [comment] 2017-07-13 12:35
I have the EXACT same Problems as @BioTurboNick.
Are you testing on VS on the Mac or under Windows?

**Comment by MatkovIvan** [comment] 2017-07-13 12:45
@KlausLoeffelmann I see that this issue has several people. I tried to reproduce on PC yesterday. Let me try on mac then

**Comment by BioTurboNick** [comment] 2017-07-13 13:22
@MatkovIvan I was seeing this on a PC. Trying to reproduce. Made a fresh Xamarin Android project and it seemed to have a whole different problem--kept getting an exception saying user canceled the login.

**Comment by MatkovIvan** [comment] 2017-07-13 13:35
@KlausLoeffelmann on mac works too for me.
@BioTurboNick this exception throws when user press on back button. I checked that login on Android works fine (I redirected to app and web page was closed) a moment ago. Could you please share this sample project to check?

**Comment by BioTurboNick** [comment] 2017-07-13 15:32
I'm trying, but it breaks in new and different ways each time I try something. I hate Android. For instance, now I'm getting a ClassNotFound exception for WebAuthenticatorNativeBrowserActivity.

**Comment by KlausLoeffelmann** [comment] 2017-07-13 16:30
@BioTurboNick: 

Are you working with Visual Studio 2017 Update 3 Preview X?
Are you working with the Xamarin Beta Libs? (25.3.x)
And if, are you possibly hosting the Xamarin.Forms stuff in a .NET Standard Library rather than in a portable class library?

@MatkovIvan : Would such a scenario be supported? Or could one of those settings be the course of such a weirdness? (I think that will be the way to go any time soon, once Xamarin released the 25.3.x Libs, because they already support .NET Standard without the PackageTargetFallback Attribute.)

**Comment by MatkovIvan** [comment] 2017-07-13 16:42
@KlausLoeffelmann Could you clarify which scenario you are talking about?

**Comment by KlausLoeffelmann** [comment] 2017-07-13 16:46
Well, I was wondering if the Azure Mobile Service Client NuGet would work already fully in a Xamarin.Forms App, where the PCL (hosting the actual Xamarin.Forms UI) would be replaced by a .NET Standard Library, and we would be using the latest (Prerelease) Xamarin.Forms and Android NuGets. All that is possible today when you set up the solution manually.

**Comment by BioTurboNick** [comment] 2017-07-13 18:04
@KlausLoeffelmann:
Visual Studio is the current release version (2017.2)
Xamarin.Forms 2.3.5.256-pre6
Xamarin.Android libraries (25.3.1)
Yes, Forms is in a .NET Standard library (required for Microsoft.Azure.Mobile.Client to install)

**Comment by KlausLoeffelmann** [comment] 2017-07-13 18:43
The only way I got that working with .NET Standard was on Visual Studio for the Mac. But then there are other challenges: The IntentFilter will not be merged with the Authentication stuff in the right way, if you add the UrlScheme to the AndroidManifest file in XML. So, currently I try a way to implement it with attributes over the MainActivity Class. But also it seems, when the App is called back by the Login, that OnCreate starts a second time. But I'm not at all sure, if this is really happening. As soon as I have a running version, I'm going to post it as a Gist a link it.

**Comment by BioTurboNick** [comment] 2017-07-13 18:47
I'm not sure I understand. The error is on launching the web browser for authentication, not on return.

**Comment by KlausLoeffelmann** [comment] 2017-07-13 18:50
I know. But not if I compiled it with VS on Mac. (But I changed so much, meanwhile, I need to test it on Win again). But when it ran, THEN the next problem occurred, and that was on return.

**Comment by BioTurboNick** [comment] 2017-07-13 18:57
Okay, but that's not this issue. This issue appears to be about mismatched dependencies.

**Comment by MatkovIvan** [comment] 2017-07-13 19:07
@BioTurboNick You may use PCL Xamarin.Forms (current stable) with .NET Standard - https://github.com/Azure/azure-mobile-apps-net-client/issues/337#issuecomment-308068815
https://github.com/dhei/azure-mobile-apps-xamarinforms-login-sample - Does this sample work for you?

**Comment by BioTurboNick** [comment] 2017-07-13 19:50
@MatkovIvan I haven't been able to get that project to work. I get a "Build action 'EmbeddedResource' is not supported by one or more of the project's targets." error for the PCL.

**Comment by KlausLoeffelmann** [comment] 2017-07-13 22:33
@MatkovIvan @BioTurboNick  

Forget what I wrote before - it was complete nonsense. Sorry for that.

Here is my repo for the bug, and I did it on the Mac:
* Create a new Android Project.
* Add the Azure Mobile Client SDK
* Update all NuGet Packages.
* Try to compile.

Result:
Target _LinkAssembliesShrink:
    /Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(1577,5): error MSB4018: The "LinkAssemblies" task failed unexpectedly.
    /Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(1577,5): error MSB4018: Mono.Linker.MarkException: Error processing method: 'System.Void Android.Support.CustomTabs.Chromium.SharedUtilities._MobileServices.CustomTabActivityHelper::LaunchUrlWithCustomTabsOrFallback(Android.App.Activity,Android.Support.CustomTabs.CustomTabsIntent,Android.Net.Uri,Android.Support.CustomTabs.Chromium.SharedUtilities._MobileServices.ICustomTabFallback)' in assembly: 'Microsoft.Azure.Mobile.Client.dll' ---> Mono.Cecil.ResolutionException: Failed to resolve System.Void Android.Support.CustomTabs.CustomTabsIntent::LaunchUrl(Android.App.Activity,Android.Net.Uri)

**Comment by BioTurboNick** [comment] 2017-07-13 22:52
@KlausLoeffelmann I guess your version is linking on compilation, while mine must be on the fly? But yeah, looks like the same issue.

**Comment by KlausLoeffelmann** [comment] 2017-07-13 23:00
I compiled Release, which resolves everything already at compile time, I suppose.

**Comment by BioTurboNick** [comment] 2017-07-13 23:18
Ah yeah, can also set Debug to do that too in Properties>Android Options. A lot easier than having to run the thing to test it!

**Comment by BioTurboNick** [comment] 2017-07-13 23:33
@MatkovIvan Also note that the sample project is using v4.0.0.

I think it's clear what happened: SDK v4 was written using API v25. But when it was released, that broke attempts to install it in projects with the default Visual Studio-included Android SDK and Xamarin default projects, which were v23-based. As noted in #348 and accepted in #349, this was seen as a bad experience, so the dependencies were dropped to v23. I guess this was done without checking why SDK v4 required Android v25.

**Comment by MatkovIvan** [comment] 2017-07-14 12:57
OK guys, I reproduced this problem.
@KlausLoeffelmann Thanks a lot for repro steps!
@BioTurboNick SDK don't really depends on API v25.

## In short
Fixed, will be available in next patch.
Workaroud for `4.0.1`: use `Xamarin.Android.Support.CustomTabs 23.3.0`.

## Detailed
This bug reproducing in next case: application use old `packages.config` instead `project.json` and custom tabs library has been force updated.
Differences between them: 
- `packages.config` contains all packages includeing dependencies of dependencies.
- `project.json` contains only *your* dependencies and it allow manage it easier.

So, "update all" behaviour is different.

After investigation, I found root cause of the problem. This is a declaration of `LaunchUrl` function in custom tabs library:

In `Xamarin.Android.Support.CustomTabs` version `23.3.0`:
```csharp
[Register("launchUrl", "(Landroid/app/Activity;Landroid/net/Uri;)V", "")]
public void LaunchUrl(Activity context, Uri url);
```

In `Xamarin.Android.Support.CustomTabs` version `25.3.1`:
```csharp
[Register("launchUrl", "(Landroid/content/Context;Landroid/net/Uri;)V", "")]
public void LaunchUrl(Context context, Uri url);
```

I couldn't found info about it in change logs, since this is auto-generated from java code. But in our case this is breaking change.

This issue inherited from `Xamarin.Auth`. It uses `CustomTabsIntent::LaunchUrl` directly instead of `CustomTabsActivityManager` despite [documentation of custom tabs](https://github.com/xamarin/AndroidSupportComponents/blob/master/customtabs/component/GettingStarted.md).
@moljac I see that you have a few issues related that in `Xamarin.Auth` too, so please note this.

PR to our `Xamarin.Auth` fork to fix this: https://github.com/Azure/azure-mobile-services-xamarin-auth/pull/11

**Comment by BioTurboNick** [comment] 2017-07-14 14:36
Ah, thanks, glad you were able to identify the cause. I'd argue that v4 did depend on v25--because that's what worked. It just seems to be a relatively easy dependency to remove?

I attempted to downgraded to Support.CustomTabs 23.3.0 (which also downgraded Support.v4 to 23.3.0 and upgraded SDK to 4.0.1), and got `java.lang.IllegalArgumentException: already added : Landroid/support/v4/accessibilityservice/AccessibilityServiceInfoCompat` when trying to build. Got a binding redirect suggestion which I implemented, but error remained. Cleaned solution then Rebuilt, no dice. 32 "Duplicate managed type found!" warnings. Xamarin.Android.Common.targets file is fingered.

Relatedly, appears this SDK is not alone in making this error: https://stackoverflow.com/questions/41179582/java-lang-nosuchmethoderror-android-support-v4-app-activitycompat-startactivity, see first answer.

**Comment by MatkovIvan** [comment] 2017-07-14 14:48
@BioTurboNick looks like Support.v4 used twice. Try remove it and re-add from nuget manager. Also after remove, close ide and delete `bin`, `obj`, `packages` folders to make next build fully "clean".

**Comment by BioTurboNick** [comment] 2017-07-14 15:59
@MatkovIvan Support.CustomTabs depends on Support.v4. And that didn't work.

**Comment by MatkovIvan** [comment] 2017-07-14 16:09
@BioTurboNick Yeah, `23.3.0` depends on it. I looked on `25.3.1` by mistake. Please share sample code or precise repro steps, with it really easier to find what is wrong.

**Comment by BioTurboNick** [comment] 2017-07-14 17:34
@MatkovIvan Okay. I don't think it'd be worth the time, but I think it suffices to say that downgrading to CustomTabs v23.3 may not be a good solution for some people.

Perhaps until the next release is out: if you're on v23 for Android libraries, use SDK v4.0.1; if you're on v25, use SDK v4.0.0.

**Comment by BioTurboNick** [comment] 2017-07-15 20:37
Ah, the reason downgrading to Support.CustomTabs 23.3.0, and thus Support.v4 23.3.0, causes this problem is that the namespaces were moved into Support.Compat for 25.3.1.  Other Support libraries strictly depend on Support.Compat 25.3.1. Mess of dependencies.

**Comment by dgerding** [comment] 2017-07-28 20:41
@MatkovIvan  Can you clarify the right approach, in light of all the above, to get an Android (Xamarin Forms) project using 4.01 to authenticate against the Azure backend using LoginAsync?

Any guidance appreciated.  Can I just pull the fix you reference?  And why does the solution reference a different/custom Xamarin.Auth.  I was using that to store credentials and tokens securely but I can't tell if I am [supposed to][not supposed to][required to] to replace the regular Xamarin.Auth nuget with the custom build targeting Azure.

Please help.
Thanks :)

**Comment by BioTurboNick** [comment] 2017-07-28 23:11
The solution is: Don't use 4.0.1. Use 4.0.0.

**Comment by MatkovIvan** [comment] 2017-07-31 07:52
Hi @dgerding
Since SDK is open-source you are able to build it by yourself. We include `Xamarin.Auth` as `internal` with changed namespaces to avoid conflicts, so if you need anything from it you should use regular `Xamarin.Auth` directly.

**Comment by KlausLoeffelmann** [comment] 2017-08-01 11:09
Hey guys,

anything new in this regard?

I'm still blocked.

4.0.0: LoginAsync never returns on Android? Anything I can do here?
4.0.1: LoginAsync crashing with missing method.

**Comment by MatkovIvan** [comment] 2017-08-01 11:29
@KlausLoeffelmann 
4.0.0: Logining, but not auto-closing form. Only manual press back button.
4.0.1: Don't update support lib, use `Xamarin.Android.Support.CustomTabs 23.3.0`.

**Comment by BioTurboNick** [comment] 2017-08-01 11:52
@MatkovIvan that may only work for 4.0.1 if you downgrade all support libraries to 23, not just CustomTabs, because they are interlinked.

**Comment by dgerding** [comment] 2017-08-09 01:35
@MatkovIvan  Between an unrelated Bcl.Build issue and this I'm dead in the water.  Please, do you have any eta for the next release?

**Comment by kdanilkov** [comment] 2017-08-09 04:29
Hi, I believe we would have the right 4.0.2   
for now I use 4.0.0 with
 public void SendOnTop()
        {
            //API 23 on metal... requires this. 4.0.0 version problem when return from browser
            Intent intent = new Intent(Forms.Context, typeof(MainActivity));
            intent.SetFlags(ActivityFlags.ReorderToFront);
            Forms.Context.StartActivity(intent);
        }

**Comment by mapgccv** [comment] 2017-10-04 19:56
I have the exact same problem, took me a while to identify it though. In my use case, I cannot downgrade the support libraries because some components I use depend on them, so I am actually dead in water.

Besides, it's quite disappointing that this _entry level_ features don't work: I have only just started with Xamarin + Azure, trying to evaluate whether we can use them for future projects or not and, by following xamarin's tutorial I find myself with a non-working solution. Difficult to think that this technology is mature enough, right?

**Comment by flatplanetpl** [comment] 2017-10-07 23:30
@mapgccv: I also cant downgrade support libs. Azure with Mobile app service was very promissing pice of tech but now... Its useful for real world scenario. Its good for demo or examples but not for serious programming.

**Comment by BioTurboNick** [comment] 2017-10-07 23:48
@mapgccv @flatplanetpl - don't downgrade support libs, you should be able to use 4.0.0, not 4.0.1.

**Comment by BioTurboNick** [comment] 2017-10-08 01:03
Though it really seems embarrassing that a point upgrade broke the library and no fix has been released in months.

**Comment by dgerding** [comment] 2017-10-08 01:40
Won't anyone from MS or Xamarin take responsibility.  Embarrassing is kind.

**Comment by flatplanetpl** [comment] 2017-10-08 19:45
@BioTurboNick 👍 Thanks! Version 4.0.0 really works! So, we waiting for new version...

**Comment by BioTurboNick** [comment] 2017-10-08 20:31
@flatplanetpl I believe the one issue on Android is that the blank webpage doesn't automatically go away after login with 4.0.0. An inconvenience for users, but at least it works.

**Comment by koniin** [comment] 2017-10-09 09:04
Debugging on my Nexus 5X running latest android release (8.0, API 26). 
I downgraded to 4.0.0 (from 4.0.1) after experiencing the MissingMethodException for CustomTabsIntent.LaunchUrl but was then greeted with this instead:

`java.lang.ClassNotFoundException: Didn't find class "md581ea35436e69ff6296ba639950f061de.WebAuthenticatorNativeBrowserActivity" on path: DexPathList[[zip file "/data/app/NotesClient.Android-IXLzDp410cG8_IM1VAZNsQ==/base.apk"],nativeLibraryDirectories=[/data/app/NotesClient.Android-IXLzDp410cG8_IM1VAZNsQ==/lib/arm, /system/fake-libs, /data/app/NotesClient.Android-IXLzDp410cG8_IM1VAZNsQ==/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]`

Compiling with build-tools\26.0.2

What else do I need to do to get this working?

**Comment by MatkovIvan** [comment] 2017-10-09 10:07
Hi @koniin
I guess you need just to clean project. That class name generated by [Xamarin Android Callable Wrapper Naming](https://developer.xamarin.com/releases/android/xamarin.android_5/xamarin.android_5.1/#Android_Callable_Wrapper_Naming) and probably this is some Xamarin build cache problem.
If it doesn't help, please clarify how to reproduce this problem to a closer look. Information that may useful - steps to repro or sample project and versions that you use (IDE, OS, Xamarin).

Next version will be soon.

**Comment by koniin** [comment] 2017-10-09 10:52
Hi @MatkovIvan 
Thanks for the hint, I removed bin and obj folders then removed the app from the phone and now it seems to be working, thanks,!

**Comment by elamalani** [comment] 2017-10-12 21:28
@BioTurboNick We released the latest version of Zumo .NET client SDK v4.0.2 today which includes the fix of this issue, please find more information [here](https://github.com/Azure/azure-mobile-apps-net-client/releases/tag/4.0.2).

**Comment by flatplanetpl** [comment] 2017-10-13 12:57
Confirmed! Android working without any issues. No need to workaround back from google page to app any more.
Thanks!

**Closed** 2017-10-13 17:14 UTC
Labels: Bug

**Comment by BioTurboNick** [comment] 2017-10-14 15:38
Confirmed as well, thank you.
