### ISSUE TITLE
Memory Leak When Accessing SyncTables with Linq on Xamarin.Android

### ISSUE THREAD

**Issue by wedgeley** [Azure/azure-mobile-apps-net-client#423] opened 2018-05-01 11:55 UTC
It is easiest to demonstrate the memory leak by starting with the QuickStart app in Azure.  I have attached a version of the QuickStart Xamarin.Android client which performs Linq queries on the local offline table.  This leaks memory:

```
var idList = await todoTable
    .Where(item => item.Text != "Missing")
    .Select(item => item.Text)
    .ToListAsync();
```

Whereas this does not:
```
var itemList = await todoTable.ToListAsync();
idList = itemList
    .Where(item => item.Text != "Missing")
    .Select(item => item.Text)
    .ToList();
```

I have found the Windows client does not leak memory, so the issue is specific to the Xamarin.Android implementation.

[viaducttodo_Xamarin_Android.zip](https://github.com/Azure/azure-mobile-apps-net-client/files/1963664/viaducttodo_Xamarin_Android.zip)

**Comment by wedgeley** [comment] 2018-05-30 09:32
I have ported my application to Windows because the Android implementation is unstable.  It has got me out of a hole with a specific customer, but it isn't a long term solution.

If I port to Linux, am I likely to experience the same memory leak?  My only option right now seems to be to avoid Linq queries altogether and access the SQL Lite database using dynamic SQL queries.

It's disappointing.

**Comment by bmourat** [comment] 2018-05-31 17:01
Hi @wedgeley 
I'm analyzing allocations from code snippets you provided and I don't see any big difference in object counts. Could you explain why you think there is a memory leak in first code snippet?

**Comment by wedgeley** [comment] 2018-05-31 18:13
Thanks for looking into this.  I use Android Profiler attached to the debug process running on an Android phone.  The memory keeps rising indefinitely on the dynamic graph it shows.  I tried to analyze deeper into the problem using memory dumps, but struggled to get very far beyond identifying a steady build up in the GC finalizer queue.

On my customer's site, you could see the memory rising in a much rougher way in the Settings -> Apps function.  After a couple of days, the app crashed.

**Comment by InquisitorJax** [comment] 2018-05-31 21:46
I'm not sure if it's related (I really hope it is) - but there seems to be a huge leak when running sync.
I've attached one of the call stacks that's hanging into all the byte[] objects.
![xamarin profiler](https://user-images.githubusercontent.com/1822976/40810050-e2d39240-652c-11e8-8410-41c61a49467b.png)

**Comment by oleksandrmykhaylyshyn** [comment] 2019-03-13 22:32
Are there any updates to this issue? We observe the same situation while synchronizing ~150k records with step/page of 5000.

**Comment by clpolet** [comment] 2019-03-19 23:33
@oleksandrmykhaylyshyn Is this also on Android? We tried to reproduced but we never could put our fingers on the leak itself.

**Comment by guperrot** [comment] 2019-03-28 22:55
Hey! 

We haven’t heard from you in a while, do you have any more questions? If so, please let us know.

**Comment by wedgeley** [comment] 2019-03-29 12:54
Well you can close it, but note:

  1. The problem is reproducible (see code I provided).
  2. It affects multiple customers (as per the comments above).
  3. It has affected us on a live customer site (and cost us reputation and development time).

But I see this technology doesn't work with the latest versions of dotNet Core, so I guess its days are numbered.  A shame as the Linux and Windows versions work very well - just the Android version is unusable.

**Comment by Quico20** [comment] 2019-03-29 19:15
I think it was a wise to reopen it!!! hopefully it can be corrected soon.

**Comment by guperrot** [comment] 2019-03-29 20:36
We close issues that have been waiting an answer from customers for some time and this one got in the batch as part of our process but it was not the original author of the issue being pinged without answer so that was a mistake, sorry for the inconvenience.

**Comment by elamalani** [comment] 2019-04-09 16:38
Hi there, thanks for reporting this issue. Unfortunately, we have deprioritized to work on this SDK issue as we are not doing any active development in Azure Mobile Apps. Please feel free to fork this repository and fix the issue.

**Comment by lassana** [comment] 2019-04-10 18:02
@elamalani Do you mean Azure Mobile Apps product is no longer supported?

**Comment by elamalani** [comment] 2019-04-10 18:23
@lassana The product is still supported but we are not investing in new feature work or fixing bugs unless there is a critical issue.

**Comment by wedgeley** [comment] 2019-04-10 18:42
Interesting definition of "supported". Failing to function on a customer site due to memory issues is not a critical issue?

**Comment by InquisitorJax** [comment] 2019-04-10 19:38
yeah - this issue basically bombed my product for android - a sync that takes minutes instead of seconds was not a usable UX ...

**Comment by adrianhall** [comment] 2020-11-03 19:01
We've just updated the library into master, which will be released as v4.2.0.  Among other things, it updates the version of SQLitePCL we use, which may be a factor here.  I will see if I can reproduce with an xUnit test.  However, it would be good to get to the bottom of what exactly is causing the leak.  

Stay tuned.  You aren't forgotten.

**Comment by adrianhall** [comment] 2021-09-17 16:57
Can anyone on this thread confirm if the leak is still present on v4.2.0 of the library?  My own testing suggests that the leak is much reduced.

**Comment by adrianhall** [comment] 2022-04-04 17:56
Since no-one has responded as to whether (or not) v4.2.0 fixes the issue, I'm going to close this issue.  Feel free to re-open if the issue persists with v4.2.0.

**Closed by adrianhall** 2022-04-04 17:56 UTC
Labels: Bug, Area-SQLite Store
